/* ──────────────────────────────────────────────────────────────────
   PROJECT DATA — 74 nodes
   Fields: id, title, domains, year, tier, status, desc, longDesc,
           role, highlights[], links[], img, color
   ────────────────────────────────────────────────────────────────── */
const PROJECTS = [
  // ─── TIER 1 — Hero ────────────────────────────────────────────────
  {
    id: 'mashrou-leila',
    title: "Mashrou' Leila",
    domains: ['sound','image','space','systems'],
    year: '2008–2022',
    tier: 1,
    status: 'Complete',
    desc: '14 years. 40+ countries. 500M+ streams. A counter-public built from sound, protest, and architectural thinking. First Middle Eastern act on the Rolling Stone cover.',
    longDesc: `Mashrou' Leila began in 2008 as a student ensemble at the American University of Beirut and became one of the most politically consequential bands of the 21st century — not despite the bans, but because of them. In fourteen years, the band played to crowds of 35,000, toured forty countries, accumulated over 500 million streams, and appeared on the cover of Rolling Stone as the first Middle Eastern act to do so.

The work was never only music. Every record was a total object: visual identity, spatial architecture, touring infrastructure, merchandise systems, press strategy. Haig served as co-founder and lead creative director, building the visual and spatial language that made the band's presence feel like an environment rather than a performance.

The bans — systematic across MENA for political and queer-visibility reasons — transformed the band into an involuntary archive of state censorship. Each prohibition was documented, categorized, appealed, and in some cases circumvented. The archive of those bans is now a research object in its own right.

The band's catalog continues to generate discovery through talent show covers (Arabs Got Talent, Star Academy, The Voice Arabic) and YouTube Shorts, with Egypt historically dominant and Iraq and Saudi Arabia emerging as new growth territories.`,
    role: 'Co-Founder, Creative Director',
    highlights: [
      'First Middle Eastern act on the Rolling Stone cover',
      '500M+ streams across 40 countries',
      'Systematically banned across MENA for political and queer-visibility content',
      'Crowds of 35,000+ at peak performances including Baalbeck International Festival',
      'Ongoing catalog discovery via YouTube Shorts (~50.9M views) and talent show covers',
    ],
    links: [
      { label: 'Rolling Stone Cover', url: 'https://www.rollingstone.com/' },
      { label: 'Spotify', url: 'https://open.spotify.com/artist/5lTMEKK6VkIGxKT6b4QDYB' },
    ],
    img: 'images/hero/mashrou-leila.jpg',
    color: '#0a0508',
  },
  {
    id: 'cartography-of-absence',
    title: 'The Cartography of Absence / Nowhere Elsewhere',
    domains: ['text'],
    year: '2022–2025',
    tier: 1,
    status: 'Active',
    desc: 'Modular dream cycle in bureaucratic forms, exploring displacement, organized into nine thematic "Houses." Autofiction manuscript (~28,000 words).',
    longDesc: `Two manuscripts in conversation. The Cartography of Absence is an earlier draft: a modular dream cycle cast in bureaucratic and clinical language — forms to be filled, reports to be filed, inventories of what has been lost. It organizes itself into nine thematic "Houses," each a different architecture of displacement.

Sometimes I Wake Up Elsewhere is its evolution: approximately 28,000 words, 62 entries, an autofiction dream cycle that lets surrealism arrive through physical detail rather than announced conceits. No named sections — sequencing does the structural work. Tonal range is intentional: funny, nightmarish, tender, mundane. Beau (cat) and Griffin (dachshund) appear throughout as literal anchors, not metaphors.

The ending stops in ordinary presence. It does not resolve or heal. It simply stops.

The governing formal principle: bureaucratic and clinical language used as literary device, not as parody — as texture. The Arabic/Armenian opening phrase كان يا ما كان / կար ու չկար (there was and there wasn't) presides over the work as its epistemological stance: holding ambiguity between fact and fiction, memory and imagination.`,
    role: 'Author',
    highlights: [
      '~28,000 words, 62 entries across two linked manuscripts',
      'Surrealism via physical detail — no announced conceits',
      'Bureaucratic language as literary texture, not parody',
      'Animals (Beau, Griffin) as literal structural anchors',
      'Full text accessible via Google Drive',
    ],
    links: [
      { label: 'Read manuscript', url: 'https://docs.google.com/document/d/1ZkARATHqVi-xWzWwY7uSW1c_gVi5YGj8HOc5f3Eb-B8/edit' },
    ],
    img: 'images/hero/space-time-tuning-machine.jpg',
    color: '#120d08',
  },
  {
    id: 'space-time-tuning-machine',
    title: 'Space Time Tuning Machine',
    domains: ['sound','space','systems'],
    year: '2020–2022',
    tier: 1,
    status: 'Complete',
    desc: 'An instrument played in reverse — tuning noises into sounds, melodies, and silence. Premiered at SXSW and The Broad Museum, Los Angeles.',
    longDesc: `The Space Time Tuning Machine is not played by making sound from silence. It works in reverse: by tuning noises into sounds, melodies, and then silence. The instrument mimics how we recollect memories and dreams — not retrieval, but reconstruction.

Its conceptual spine is a wandering troubadour who wakes with no memory of songs. They find broken instruments. With a migrating crane with broken wings, they build a machine to guide their way home. The crane is the navigator. The machine is the score. Silence is the destination.

The work premiered at SXSW 2022 and The Broad Museum in Los Angeles. It is a cross-disciplinary body of research on living, longing, and grieving in exile — rendered not as sentiment but as spatial and acoustic architecture.

Conceptual lineage: William Basinski (Disintegration Loops), The Caretaker, King Tubby, Brian Eno, Pauline Oliveros (Deep Listening). The tradition of music as excavation rather than construction.`,
    role: 'Artist, Composer, Spatial Designer',
    highlights: [
      'World premiere at SXSW 2022, Austin',
      'Presented at The Broad Museum, Los Angeles',
      'Subtractive instrument: tuning noises toward silence',
      'Research on exile, longing, and acoustic memory',
      'Lineage: Basinski, Caretaker, Oliveros, Eno, King Tubby',
    ],
    links: [
      { label: 'SXSW Archive', url: 'https://www.sxsw.com/' },
      { label: 'The Broad', url: 'https://www.thebroad.org/' },
    ],
    img: 'images/hero/space-time-tuning-machine.jpg',
    color: '#0d1208',
  },

  // ─── TIER 2 — Flagship ─────────────────────────────────────────────
  {
    id: 'derive-engine',
    title: 'DERIVE',
    domains: ['code','systems'],
    year: '2024',
    tier: 2,
    status: 'Active',
    desc: 'Drift/navigation framework. Part of the Meaning Stack Architecture. GitHub repo.',
    longDesc: `DERIVE takes its name from the Situationist practice of the dérive — unplanned, psychogeographically guided traversal of urban space. Applied to code, it is a drift/navigation framework that treats a software system as terrain to be walked rather than executed.

Part of the Meaning Stack Architecture on GitHub, DERIVE sits at the layer where raw movement through a codebase becomes interpretable — a pathfinder that surfaces not just what code does but how it connects, accumulates, and erodes over time.

The framework operates on graph structures and temporal logs, producing visualizations of code drift: the natural tendency of systems to migrate away from their original intent as entropy accumulates across contributors and time.`,
    role: 'Architect, Developer',
    highlights: [
      'Situationist dérive methodology applied to software navigation',
      'Part of the Meaning Stack Architecture (GitHub)',
      'Surfaces code drift — entropy accumulation over time',
      'Graph-based traversal of living codebases',
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/haigpapa/DERIVE' },
    ],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#080c12',
  },
  {
    id: 'hah-was-sieve',
    title: 'HAH-WAS',
    domains: ['code','systems'],
    year: '2024',
    tier: 2,
    status: 'Active',
    desc: 'Sieve/filter system. Part of the Meaning Stack Architecture. GitHub repo.',
    longDesc: `HAH-WAS is a sieve and filter system — the layer of the Meaning Stack Architecture that decides what passes through and what does not. Named for the Arabic dual form: هاو واس, the one who sifts and the act of sifting simultaneously.

In a stack where meaning is constructed across layers from raw material to cultural resonance, a sieve is necessary. HAH-WAS implements configurable filter chains that can be composed, inverted, and versioned — so the question of what belongs to a project is itself a research artifact, not a fixed decision.

The system is designed to be domain-agnostic: it filters code, text, audio metadata, and archival records using the same compositional logic.`,
    role: 'Architect, Developer',
    highlights: [
      'Named for the Arabic dual form of sifting',
      'Composable, invertible filter chains',
      'Domain-agnostic: code, text, audio, archive',
      'Part of the Meaning Stack Architecture (GitHub)',
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/haigpapa/HAH-WAS' },
    ],
    img: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    color: '#0a1520',
  },
  {
    id: 'storylines-graph',
    title: 'STORYLINES',
    domains: ['code','text'],
    year: '2024',
    tier: 2,
    status: 'Active',
    desc: 'Graph-based narrative tool. Exploring how stories can be structured as navigable networks rather than linear sequences.',
    longDesc: `STORYLINES is built on a conviction: narrative is fundamentally non-linear, and linear presentation is a compression artifact, not a property of story itself. The tool models narrative as a directed graph where nodes are scenes, beats, or moments and edges are the forces that connect them — causality, contrast, rhyme, echo, dread.

The interface allows a writer to see their story as topology: which moments have the most gravity, where the graph thins, what the path of least resistance through the material actually is. Navigation through the graph is the editing process.

Built in React with a D3 force simulation backend. Export formats include both linear reading order (for traditional publication) and the graph itself (for research and archival).`,
    role: 'Architect, Developer',
    highlights: [
      'Narrative as directed graph, not linear sequence',
      'Gravity mapping: which scenes carry the most connective weight',
      'D3 force simulation backend',
      'Dual export: linear reading order + graph topology',
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/haigpapa/STORYLINES' },
    ],
    img: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80',
    color: '#0c0a14',
  },
  {
    id: '3d-beat-synth',
    title: '3D-Beat-Synth',
    domains: ['code','sound'],
    year: '2024',
    tier: 2,
    status: 'Complete',
    desc: '3D beat synthesis. Audio-visual instrument built in the browser using React Three Fiber and Web Audio API.',
    longDesc: `3D-Beat-Synth is a browser-native audio-visual instrument: a three-dimensional beat matrix where rhythm is spatially arranged rather than linearly sequenced. Each beat cell is a physical object in 3D space, and the act of composing a rhythm is the act of sculpting a form.

Built with React Three Fiber for the 3D environment and the Web Audio API for synthesis. The synthesis engine supports layered sample playback, envelope control, and real-time spatial audio positioning — so the stereo field of the output mirrors the spatial arrangement of the composition.

The project tests a hypothesis: that making rhythm visible and spatial changes how composers relate to it — adding a kinesthetic, architectural dimension to a process usually experienced as purely temporal.`,
    role: 'Developer, Sound Designer',
    highlights: [
      'Beat matrix arranged in 3D space, not linear grids',
      'React Three Fiber + Web Audio API, fully browser-native',
      'Stereo field mirrors the spatial arrangement of the composition',
      'Rhythm as sculpture',
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/haigpapa/3D-Beat-Synth' },
    ],
    img: 'https://images.unsplash.com/photo-1536852841012-1d10af86ae26?w=800&q=80',
    color: '#080a14',
  },
  {
    id: 'music-engines',
    title: 'music-engines',
    domains: ['code','sound','systems'],
    year: '2024',
    tier: 2,
    status: 'Active',
    desc: 'AI music research on maqam/Arabic localization gaps in generative audio models. The Localization Gap research engine.',
    longDesc: `music-engines is the technical infrastructure behind the Localization Gap research: a Python-based pipeline that systematically generates, annotates, and analyzes AI-produced music for evidence of cultural erasure.

The pipeline red-teams Suno, Udio, and MusicLM with prompts designed to elicit Arabic maqam structures, microtonal systems, and non-Western harmonic resolution. The output is logged, transcribed (via MIDI extraction and pitch analysis), and compared against ground-truth recordings from the tradition.

The resulting dataset — 427+ tracks with full metadata, annotation taxonomy covering emotional arc, arousal, motifs, themes, and valence — is the evidentiary base for the Localization Gap thesis. The gap is not a bug. It is a design pattern: AI systems defaulting to Western harmonic frameworks because that is what they were trained on.`,
    role: 'Researcher, Developer',
    highlights: [
      'Python API pipeline red-teaming Suno, Udio, MusicLM',
      '427+ generated and annotated tracks',
      'Pitch analysis against maqam ground-truth recordings',
      'Evidence base for the Localization Gap thesis',
    ],
    links: [
      { label: 'GitHub', url: 'https://github.com/haigpapa/music-engines' },
    ],
    img: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
    color: '#0d0810',
  },
  {
    id: 'kardia-system',
    title: 'Kardia',
    domains: ['code','sound','systems'],
    year: '2026',
    tier: 2,
    status: 'Complete',
    desc: 'Mobile biofeedback instrument transforming heart rate data into sound via the Iso-Principle. Full PRD completed January 2026.',
    longDesc: `Kardia is a mobile biofeedback instrument built on the Iso-Principle: a technique from music therapy that begins by matching a user's physiological state with sonic texture, then gradually guides it toward clarity as the body calms. The instrument doesn't add music to your state. It excavates music from it.

The interaction model: a three-zone vertical drag interface. Heart rate (via smartwatch API) sets the initial density and harmonic complexity of the output. The user's hands shape its character. As the body calms, the sound thins — not toward silence but toward clarity. The BPM is never displayed. It would create anxiety loops.

Full PRD completed January 2026. Stack: React Native (Expo), AudioKit (iOS), Oboe (Android), React Native Skia. Offline-first: local SQLite, no account required for core use. Scala file export for cardiac scales.`,
    role: 'Product Architect, Sound Designer',
    highlights: [
      'Iso-Principle: match physiological state, then guide toward calm',
      'Heart rate shapes harmonic density — BPM never displayed',
      'React Native + AudioKit (iOS) + Oboe (Android)',
      'Offline-first, no account required for core use',
      'Full PRD: 60+ pages, completed January 2026',
    ],
    links: [],
    img: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    color: '#0a0d14',
  },
  {
    id: 'loop-corridor',
    title: 'Loop Corridor',
    domains: ['code','space'],
    year: '2024',
    tier: 2,
    status: 'Complete',
    desc: 'Meditative art game with bureaucratic purgatory corridors that mutate across loop counts. Systems art meets game design.',
    longDesc: `Loop Corridor is a meditative art game built around a single mechanical idea: the corridor mutates with each loop. The player walks through bureaucratic purgatory — forms, waiting rooms, filing systems, numbered doors — and each return changes the geometry in ways that are almost imperceptible at first, then unmistakably different.

The design reference is Kafka's antechambers and Borges's architectures: spaces that accumulate dread not through threat but through sameness-that-isn't-quite. The longer you walk, the more you understand you have always been here.

Built in the browser using Three.js for spatial rendering and a procedural mutation engine that tracks loop count and applies incremental transformations to every corridor parameter: width, ceiling height, lighting color temperature, audio density, door numbering system.`,
    role: 'Game Designer, Developer',
    highlights: [
      'Corridor mutates imperceptibly with each loop',
      'Bureaucratic purgatory aesthetic: Kafka, Borges, Tarkovsky',
      'Three.js spatial rendering + procedural mutation engine',
      'Dread through sameness, not threat',
    ],
    links: [],
    img: 'https://images.unsplash.com/photo-1550438089-3d4be7c8a7cc?w=800&q=80',
    color: '#080c10',
  },
  {
    id: 'codeverse-explorer',
    title: 'Codeverse Explorer / Telescode',
    domains: ['code','space'],
    year: '2024',
    tier: 2,
    status: 'Complete',
    desc: 'Spatial computing interface for code architecture using acetate-layer depth navigation. Visualizes codebases as inhabitable spaces.',
    longDesc: `Codeverse Explorer treats a codebase as a building. Files are rooms. Imports are corridors. Dependencies are load-bearing walls. The interface lets you inhabit rather than browse.

The acetate-layer navigation model stacks abstraction levels as transparent planes: at ground level, individual functions. One layer up: modules. Another: subsystems. The user navigates depth by raising and lowering through these planes, maintaining spatial orientation across abstraction levels.

Telescode is the companion concept: a telepresence interface for pair programming and code review where the spatial metaphor persists. Two people inhabit the same codeverse simultaneously, each with their own cursor and spatial position.

Built with Three.js and a custom spatial indexing engine that parses ASTs into spatial coordinate systems.`,
    role: 'Architect, Developer',
    highlights: [
      'Codebase as inhabitable space: files as rooms, imports as corridors',
      'Acetate-layer depth navigation across abstraction levels',
      'Telescode: telepresence pair programming in shared spatial context',
      'Three.js + AST-to-coordinate spatial parser',
    ],
    links: [],
    img: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80',
    color: '#080d0d',
  },
  {
    id: 'lede-nyc',
    title: 'Lede.nyc',
    domains: ['code','systems'],
    year: '2025',
    tier: 2,
    status: 'Active',
    desc: 'Autonomous civic intelligence engine for NYC. Ingests municipal datasets and synthesizes neighborhood briefings — zero editorial intervention.',
    longDesc: `Lede.nyc is an autonomous civic intelligence platform that ingests New York City's open municipal datasets — permits, 311 complaints, property records, DOB filings, NYPD data, school data — and synthesizes them into neighborhood-level briefings without human editorial intervention.

The product sits in the missing middle between social panic platforms (Nextdoor, Citizen) and static real estate portals (StreetEasy). It is not a news site. It is an intelligence layer: structured, searchable, and updated continuously from primary source data.

Key features include the Lease Due Diligence Engine (surfacing building violation history before you sign), Scaffold Duration Forecasting (predicting how long that sidewalk shed will actually be there), Block Mood Forecast, and Canine Commute Optimizer.

Stack: Next.js, BigQuery, MCP, hybrid LLM orchestration. Revenue model: five tiers from free acquisition to institutional API access; target $5M+ ARR.`,
    role: 'Founder, Architect',
    highlights: [
      'Zero editorial intervention — primary source municipal data',
      'Lease Due Diligence Engine, Scaffold Duration Forecasting',
      'The missing middle between Nextdoor and StreetEasy',
      'Next.js + BigQuery + MCP + hybrid LLM orchestration',
      'Five-tier revenue model, $5M+ ARR target',
    ],
    links: [
      { label: 'lede.nyc', url: 'https://lede.nyc' },
    ],
    img: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    color: '#060a10',
  },
  {
    id: 'mekena-nyc-initiative',
    title: 'MEKENA NYC',
    domains: ['space','systems'],
    year: '2023',
    tier: 2,
    status: 'Active',
    desc: 'Artist residency in Queens, NY. Builds infrastructure for experimental and interdisciplinary practice. Westbeth Safe Haven partner.',
    longDesc: `MEKENA NYC is an artist residency in Queens, New York, founded by Haig Papazian to build infrastructure for experimental and interdisciplinary practice — specifically for artists working across domains that existing institutions struggle to categorize.

The name MEKENA draws from the Arabic مكان (makān) — place, location, position. A site. The residency is not a gallery or a studio program. It is infrastructure: production support, emergency housing access, critical reading groups, and technical collaboration across disciplines.

MEKENA is a Westbeth Safe Haven partner, providing emergency residency access for artists in crisis. It operates on the principle that the most important thing an institution can do for artists is reduce the friction between practice and sustenance.`,
    role: 'Founder, Director',
    highlights: [
      'Artist residency founded 2023, Queens, New York',
      'Infrastructure model: production support, emergency housing, technical collaboration',
      'Westbeth Safe Haven partner — emergency residency access',
      'Named for Arabic مكان (place, position, site)',
    ],
    links: [],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#080c12',
  },
  {
    id: 'sometimes-i-wake-up-elsewhere',
    title: 'Sometimes I Wake Up Elsewhere',
    domains: ['text'],
    year: '2022–2025',
    tier: 2,
    status: 'Active',
    desc: 'Autofiction manuscript. ~28,000 words. 62 entries. Dream cycle exploring displacement, exile, and ordinary presence.',
    longDesc: `Sometimes I Wake Up Elsewhere is an autofiction dream cycle: approximately 28,000 words across 62 entries. It is the active manuscript; The Cartography of Absence is its predecessor.

The book contains multitudes of tone: funny, nightmarish, tender, mundane — often inside the same entry. Beau (the cat) and Griffin (the dachshund) are literal presences throughout, not symbolic ones. The animals are not metaphors for anything. They are there because they are there.

Surrealism arrives through physical detail. Nothing is announced as strange. The bureaucratic language of the earlier manuscript has been absorbed and metabolized: it surfaces now as texture in the narrator's thinking, not as formal device.

The ending stops in ordinary presence. It does not resolve or heal. A person makes coffee. The dog is on the floor. The cat is on the window ledge. The book ends.`,
    role: 'Author',
    highlights: [
      '~28,000 words, 62 entries',
      'Autofiction / dream cycle: funny, nightmarish, tender, mundane',
      'Surrealism via physical detail — nothing announced as strange',
      'Animals as literal presences, not metaphors',
      'Ending: ordinary presence, no resolution',
    ],
    links: [
      { label: 'Read manuscript', url: 'https://docs.google.com/document/d/1oVWHiNzhKwPwda7HJeF5KKn971ziKBT_MbIfCe8y_5k/edit' },
    ],
    img: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=800&q=80',
    color: '#0a0810',
  },
  {
    id: 'crane-song',
    title: 'The Crane Song',
    domains: ['text'],
    year: '2024',
    tier: 2,
    status: 'Complete',
    desc: 'Short story expanded to ~10,000 words. A Lebanese-Armenian exile in Brooklyn encounters a broken AI bird from a virtual Beirut. Character: Sarkis Melkonian.',
    longDesc: `The Crane Song follows Sarkis Melkonian, a Lebanese-Armenian exile in Brooklyn, who encounters a broken AI bird generated from a virtual reconstruction of Beirut — a city the AI has assembled from photographs, satellite data, and refugee testimonies, none of which agree with each other.

The bird cannot fly. It navigates by memory, which is to say it navigates by error. Sarkis is trying to find an apartment. The story takes place in a single afternoon.

The narrative uses bureaucratic and clinical language as a literary device — not parody but texture. Maintenance requests, incident reports, intake forms. The violence of the administrative voice applied to the experience of displacement.

The story was originally a short form that expanded under its own weight to approximately 10,000 words.`,
    role: 'Author',
    highlights: [
      '~10,000 words, expanded from short story form',
      'Character: Sarkis Melkonian, Lebanese-Armenian exile in Brooklyn',
      'AI bird reconstructed from a contradictory archive of Beirut',
      'Clinical and bureaucratic language as literary texture',
    ],
    links: [
      { label: 'Read manuscript', url: 'https://docs.google.com/document/d/1m3rg1eZY73AN41wGafHw2fv0J9jREVbY/edit' },
    ],
    img: 'https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?w=800&q=80',
    color: '#080a0e',
  },
  {
    id: 'colors-baby',
    title: 'Colors Baby',
    domains: ['image','sound'],
    year: '2024',
    tier: 2,
    status: 'Complete',
    desc: 'AI music video project using Suno, Sora, Kling, Veo, and Minimax. Exploring generative cinema as compositional form.',
    longDesc: `Colors Baby is an AI music video produced using Suno (audio), Sora, Kling, Veo, and Minimax (video generation). It is an attempt to treat the AI music video not as a novelty but as a compositional form — where the decisions made about prompts, model selection, edit rhythm, and color grading constitute the artistic practice.

The project explores what it means to direct without directing: to establish a vision and then negotiate with probabilistic image machines to arrive at something that looks like intention. The gap between the two is where the work lives.

Colors Baby was produced as part of ongoing research into AI-generated visual music and the cultural politics of who gets to see themselves in machine-generated imagery.`,
    role: 'Director, Composer',
    highlights: [
      'Full production pipeline: Suno + Sora + Kling + Veo + Minimax',
      'Generative cinema as compositional practice',
      'Directing without directing: vision via probabilistic negotiation',
      'Part of ongoing AI visual music research',
    ],
    links: [],
    img: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    color: '#0d0810',
  },
  {
    id: 'localization-gap-audit',
    title: 'The Localization Gap',
    domains: ['code','sound','systems'],
    year: '2024',
    tier: 2,
    status: 'Active',
    desc: '427+ tracks generated and annotated via Python API pipelines. Red-teaming Suno, Udio, and MusicLM for Arabic maqam erasure. Original AI research.',
    longDesc: `The Localization Gap is original AI research built on a specific observation: generative audio systems systematically erase cultural specificity, defaulting to Western harmonic frameworks when asked to produce Arabic, Persian, or other non-Western musical content.

The evidence base is 427+ tracks generated and annotated via Python API pipelines that red-teamed Suno, Udio, and MusicLM. Prompts were designed to elicit maqam structures, microtonal systems, quarter-tone intervals, and non-Western cadential patterns. The output was transcribed, analyzed spectrally, and compared against ground-truth recordings.

The gap is not a bug. It is a design consequence: AI systems reflect their training data, and Western popular music dominates training data at a ratio that makes erasure structural.

The research is the intellectual spine of Haig's Anthropic application (Solutions Architect, Applied AI — Creatives) and of Walaw Studio's AI research positioning. Its scope extends beyond music to AI's general failure to hold cultural specificity at scale.`,
    role: 'Researcher, Lead Investigator',
    highlights: [
      '427+ generated tracks, fully annotated',
      'Red-teaming Suno, Udio, MusicLM for maqam erasure',
      'Spectral analysis + MIDI transcription against ground-truth recordings',
      'The gap is structural, not incidental',
      'Intellectual spine of Anthropic application and Walaw Studio AI positioning',
    ],
    links: [],
    img: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    color: '#0a1520',
  },
  {
    id: 'walaw-studio',
    title: 'Walaw Studio',
    domains: ['systems'],
    year: '2023',
    tier: 2,
    status: 'Active',
    desc: 'Cultural strategy practice working across AI research, spatial design, sound, and systems. Named for the Arabic letter و (waw) as waveform, heartbeat, hook.',
    longDesc: `Walaw Studio is Haig Papazian's cultural strategy practice, founded 2023. It works across AI research, spatial design, sound, and systems — treating these not as separate services but as a single connected inquiry into how meaning is constructed and distributed.

The name derives from the Arabic letter و (waw), which reads simultaneously as a waveform, a heartbeat spike, and a hook. The conjunction "and" in Arabic — the simplest connector, the thing that holds separate elements in relation. The logo is stroke-only, square linecaps, pixel squares as diacritics.

Current focus areas: the Localization Gap research, civic intelligence systems (Lede.nyc), and cultural infrastructure (MEKENA NYC). The studio operates at the intersection of cultural specificity and generative systems — where AI's defaults most visibly fail.`,
    role: 'Founder, Principal',
    highlights: [
      'Cultural strategy practice founded 2023',
      'Named for Arabic و (waw) — waveform, heartbeat, hook, conjunction',
      'Focus: AI research, spatial design, sound, cultural infrastructure',
      'Clients and projects: Lede.nyc, MEKENA, Localization Gap',
    ],
    links: [
      { label: 'walaw.studio', url: 'https://walaw.studio' },
    ],
    img: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    color: '#0c0c08',
  },

  // ─── TIER 3 — Archive ──────────────────────────────────────────────
  {
    id: 'photon-plus',
    title: 'Photon+',
    domains: ['code','sound'],
    year: '2024',
    tier: 3,
    status: 'Complete',
    desc: 'Digital twin of the Space Time Tuning Machine. Grid-based browser instrument using React Three Fiber and Web Audio API.',
    longDesc: `Photon+ is the digital twin of the Space Time Tuning Machine — a grid-based browser instrument that translates the spatial and subtractive logic of the live performance work into an interactive web object. Built with React Three Fiber and Web Audio API. Part of the Meaning Stack Architecture on GitHub.`,
    role: 'Developer',
    highlights: ['Digital twin of Space Time Tuning Machine', 'React Three Fiber + Web Audio API', 'Part of Meaning Stack Architecture'],
    links: [{ label: 'GitHub', url: 'https://github.com/haigpapa/photon-plus' }],
    img: 'https://images.unsplash.com/photo-1579403124614-197f69d8187b?w=800&q=80',
    color: '#0c0a14',
  },
  {
    id: 'systems-choreography',
    title: 'Choreography of Systems',
    domains: ['systems'],
    year: '2024',
    tier: 3,
    status: 'Complete',
    desc: 'Core conceptual framework as code artifact. Treating interconnected disciplines as choreography rather than engineering.',
    longDesc: `Choreography of Systems is Haig's core conceptual framework rendered as a code artifact. The central argument: when working across interconnected disciplines, authorship language (choreography, score, atlas) is more accurate than engineering language (framework, pipeline, engine). GitHub repo in the Meaning Stack Architecture.`,
    role: 'Theorist, Developer',
    highlights: ['Authorship language vs engineering language', 'Core framework for cross-disciplinary practice', 'GitHub: Meaning Stack Architecture'],
    links: [{ label: 'GitHub', url: 'https://github.com/haigpapa/choreography-of-systems' }],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'ai-music-archive',
    title: 'AI Music Catalog',
    domains: ['code','sound'],
    year: '2024',
    tier: 3,
    status: 'Complete',
    desc: '401-track AI-assisted catalog with Notion/Excel taxonomy covering emotional arc, arousal, motifs, themes, valence.',
    longDesc: `A 401-track catalog of AI-assisted music, annotated with a custom taxonomy in Notion and Excel. Fields: emotional arc, arousal level, dominant motif, thematic content, valence, cultural register. The catalog was built as an evidence base for the Localization Gap research and as a practical library for production use.`,
    role: 'Researcher, Curator',
    highlights: ['401 tracks, fully annotated', 'Custom taxonomy: emotional arc, arousal, motif, valence', 'Evidence base for Localization Gap research'],
    links: [],
    img: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
    color: '#0d0810',
  },
  {
    id: 'cost-of-queer-arab',
    title: 'The Cost of Being Queer and Arab',
    domains: ['text'],
    year: '2019',
    tier: 3,
    status: 'Published',
    desc: 'Op-Ed published in The New York Times. On identity, exile, and the political dimensions of queer Arab existence.',
    longDesc: `Op-Ed published in The New York Times. Written in the wake of a Mashrou' Leila concert being cancelled in Egypt following pressure from religious authorities — a ban that effectively ended the band's ability to perform in the Arab world. The piece navigates identity, exile, queer Arab existence, and what it means to have your voice systematically removed from its context of origin.`,
    role: 'Author',
    highlights: ['Published in The New York Times, 2019', 'Written in the wake of Egypt concert ban', 'On queer Arab identity and systematic cultural silencing'],
    links: [],
    img: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'rolling-stone-cover',
    title: 'Rolling Stone Cover',
    domains: ['image','sound'],
    year: '2019',
    tier: 3,
    status: 'Published',
    desc: "Mashrou' Leila became the first Middle Eastern act on the cover of Rolling Stone magazine. Art direction and visual identity.",
    longDesc: `In 2019, Mashrou' Leila became the first Middle Eastern act to appear on the cover of Rolling Stone magazine. Haig led the art direction and visual identity for the shoot and surrounding campaign, working to ensure the visual language maintained the band's own aesthetic rather than defaulting to Western editorial conventions for representing Arab subjects.`,
    role: 'Art Director, Creative Director',
    highlights: ['First Middle Eastern act on Rolling Stone cover', 'Full art direction and visual identity', 'Resisted Western editorial conventions for Arab representation'],
    links: [],
    img: 'images/hero/rolling-stone-cover.jpg',
    color: '#0d0810',
  },
  {
    id: 'harmonic-field-research',
    title: 'The Harmonic Field',
    domains: ['sound','code'],
    year: '2024',
    tier: 3,
    status: 'Active',
    desc: 'Research project exploring spatial harmonics and the relationship between architectural acoustics and generative music systems.',
    longDesc: `The Harmonic Field investigates the relationship between architectural acoustics and generative music: how the acoustic properties of a space (reverberation time, modal distribution, material absorption) can be used as compositional parameters rather than constraints to be corrected. Research in progress.`,
    role: 'Researcher',
    highlights: ['Architectural acoustics as compositional parameters', 'Spatial harmonics and generative systems', 'Active research, 2024–'],
    links: [],
    img: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=800&q=80',
    color: '#0a0c12',
  },
  {
    id: 'resonance-atlas',
    title: 'Resonance Atlas',
    domains: ['sound','systems'],
    year: '2024',
    tier: 3,
    status: 'Active',
    desc: 'A cartographic approach to mapping sonic territories — charting the cultural geography of musical systems across regions and traditions.',
    longDesc: `Resonance Atlas applies cartographic methods to sonic territories: mapping the geographic distribution of musical systems, modal traditions, and instrument families as overlapping cultural geographies rather than discrete national categories. An atlas of sound as territory.`,
    role: 'Researcher, Cartographer',
    highlights: ['Musical systems mapped as overlapping cultural geographies', 'Cartographic methods applied to sonic tradition', 'Active research atlas'],
    links: [],
    img: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80',
    color: '#0a100c',
  },
  {
    id: 'architecture-in-low-res',
    title: 'Architecture in Low-Res',
    domains: ['space','image'],
    year: '2023',
    tier: 3,
    status: 'Complete',
    desc: 'Research on compressed and degraded representations of built space — architecture as it appears in low-resolution images, memories, and approximations.',
    longDesc: `Architecture in Low-Res examines what happens to built space when it is compressed: in low-resolution photographs, in refugee testimony, in memory, in satellite imagery, in architectural drawings made without site access. The research argues that degraded representation is not a failure state but a condition of knowledge about space — particularly for spaces that are contested, destroyed, or inaccessible.`,
    role: 'Researcher',
    highlights: ['Degraded representation as a knowledge condition', 'Low-res photography, testimony, satellite imagery, memory', 'Architecture in inaccessible and destroyed spaces'],
    links: [],
    img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'menara-infrastructure',
    title: 'Menara Infrastructure',
    domains: ['space','systems'],
    year: '2022',
    tier: 3,
    status: 'Complete',
    desc: 'Spatial systems project examining the infrastructural logic of minaret architecture as communication and orientation technology.',
    longDesc: `Menara Infrastructure reads the minaret not as a religious symbol but as communication technology: a distributed network of orientation devices that structured sound, time, and navigation across the pre-modern city. The project examines the minaret's infrastructural logic and asks what contemporary urban communication networks inherit from it.`,
    role: 'Researcher, Spatial Designer',
    highlights: ['Minaret as distributed communication network', 'Sound, time, navigation as urban infrastructure', 'Pre-modern city as networked system'],
    links: [],
    img: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800&q=80',
    color: '#080c10',
  },
  {
    id: 'ghost-city-sculpture',
    title: 'Ghost City',
    domains: ['space','image'],
    year: '2021',
    tier: 3,
    status: 'Complete',
    desc: 'Sculptural intervention exploring the phantom presence of demolished and destroyed urban fabric — the negative space of buildings that no longer exist.',
    longDesc: `Ghost City is a sculptural intervention concerned with negative space: the volume occupied by buildings that have been demolished, destroyed, or erased. The work makes visible the phantom presence of urban fabric that no longer exists by casting the absence as a positive form — a city of what was there.`,
    role: 'Artist, Spatial Designer',
    highlights: ['Phantom presence of demolished urban fabric', 'Negative space cast as positive form', 'Sculptural intervention'],
    links: [],
    img: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80',
    color: '#0a0a0a',
  },
  {
    id: 'the-labyrinth',
    title: 'The Labyrinth',
    domains: ['space','code'],
    year: '2022',
    tier: 3,
    status: 'Complete',
    desc: 'Procedural spatial narrative — an architectural labyrinth that generates itself from cultural memory data. Computational design meets archival practice.',
    longDesc: `The Labyrinth is a procedural spatial narrative: an architectural space that generates itself from cultural memory data. The labyrinth's geometry is derived from archival material — oral histories, family photographs, cadastral maps — processed through a generative algorithm that translates narrative structure into spatial structure. The labyrinth you navigate is the memory.`,
    role: 'Architect, Developer',
    highlights: ['Procedural geometry derived from archival and oral history data', 'Narrative structure translated into spatial structure', 'Computational design + archival practice'],
    links: [],
    img: 'https://images.unsplash.com/photo-1550438089-3d4be7c8a7cc?w=800&q=80',
    color: '#080c10',
  },
  {
    id: 'the-forgery',
    title: 'The Forgery',
    domains: ['image','text'],
    year: '2023',
    tier: 3,
    status: 'Complete',
    desc: 'An investigation into authenticity, reproduction, and the ethics of visual citation — what it means to copy in the age of generative AI.',
    longDesc: `The Forgery is an investigation into authenticity, reproduction, and visual citation in the age of generative AI. What does it mean to copy when copying is automatic? What does it mean to forge when the original and the reproduction are indistinguishable? The project examines these questions through both critical essay and visual practice.`,
    role: 'Artist, Writer',
    highlights: ['Authenticity and reproduction in the age of generative AI', 'Visual citation ethics', 'Critical essay + visual practice'],
    links: [],
    img: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800&q=80',
    color: '#100c08',
  },
  {
    id: 'caspian-mare-drift',
    title: 'Caspian Mare Drift',
    domains: ['sound','space'],
    year: '2021',
    tier: 3,
    status: 'Complete',
    desc: 'Ambient composition and spatial installation exploring the acoustic geography of the Caspian region — contested territories rendered in sound.',
    longDesc: `Caspian Mare Drift is an ambient composition and spatial installation built from field recordings gathered across the Caspian basin — a body of water contested between five nations, subject to constantly shifting territorial claims, and acoustically distinct across its shores. The work renders the geopolitical instability of the region through its sonic geography.`,
    role: 'Composer, Artist',
    highlights: ['Field recordings from the Caspian basin', 'Geopolitical instability rendered as sonic geography', 'Five contested national territories in one body of water'],
    links: [],
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    color: '#0a0e12',
  },
  {
    id: 'project-agora',
    title: 'Project Agora',
    domains: ['space','systems'],
    year: '2020',
    tier: 3,
    status: 'Complete',
    desc: 'A proposal for civic space as platform — rethinking the public square as programmable infrastructure for community assembly and deliberation.',
    longDesc: `Project Agora is an architectural and systems proposal: the public square as programmable civic infrastructure. Not a plaza with built-in LED screens, but a reconfigurable spatial system that can support assembly, deliberation, protest, performance, and rest simultaneously — different communities using the same space according to different protocols.`,
    role: 'Architect, Systems Designer',
    highlights: ['Public square as programmable civic infrastructure', 'Simultaneous, protocol-governed multiple uses', 'Architecture as civic platform'],
    links: [],
    img: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    color: '#0a0c10',
  },
  {
    id: 'bureaucratic-surrealism',
    title: 'Bureaucratic Surrealism',
    domains: ['text','systems'],
    year: '2023',
    tier: 3,
    status: 'Complete',
    desc: 'A literary-conceptual project using administrative language, forms, and procedures as the primary material for surrealist narrative construction.',
    longDesc: `Bureaucratic Surrealism is a literary-conceptual project that takes administrative language, forms, and procedures as its raw material. The project produces a body of texts — incident reports, intake forms, maintenance requests, audit trails — in which the surreal emerges not from the content but from the relentless application of administrative logic to experiences that resist it.`,
    role: 'Author',
    highlights: ['Administrative language as surrealist raw material', 'Incident reports, intake forms, audit trails as literary genre', 'Surrealism from relentless bureaucratic logic, not content'],
    links: [],
    img: 'https://images.unsplash.com/photo-1590608897129-79da98d15969?w=800&q=80',
    color: '#100c08',
  },
  {
    id: 'mobius-engine',
    title: 'Möbius Engine',
    domains: ['code','sound'],
    year: '2023',
    tier: 3,
    status: 'Complete',
    desc: 'A looping audio engine that inverts its own structure — compositions that consume themselves and regenerate from the remnants.',
    longDesc: `The Möbius Engine is a looping audio engine with a self-inverting architecture: compositions built with it consume themselves over time, each loop eating a portion of its own structure and regenerating from the remnants. The result is music that degrades, mutates, and eventually arrives somewhere its original form could not have predicted. Influenced by William Basinski's Disintegration Loops.`,
    role: 'Developer, Composer',
    highlights: ['Self-inverting audio architecture', 'Compositions that consume and regenerate from themselves', 'Influence: Basinski, Disintegration Loops'],
    links: [],
    img: 'https://images.unsplash.com/photo-1536852841012-1d10af86ae26?w=800&q=80',
    color: '#080a14',
  },
  {
    id: 'souad-novella',
    title: 'Souad (Novella)',
    domains: ['text'],
    year: '2022',
    tier: 3,
    status: 'Complete',
    desc: 'A novella-length work of autofiction exploring diaspora identity through the figure of a Lebanese grandmother navigating Queens, New York.',
    longDesc: `Souad is a novella-length autofiction following a Lebanese grandmother navigating Queens, New York — the same borough as MEKENA, the same diaspora communities that shaped Haig's own geography. The character of Souad is assembled from fragments of multiple women, none of them composites exactly. The form is autofiction: the "I" is present but untrustworthy.`,
    role: 'Author',
    highlights: ['Novella-length autofiction', 'Lebanese grandmother in Queens, New York', 'Diaspora identity, assembled from fragments'],
    links: [{ label: 'Read manuscript', url: 'https://docs.google.com/document/d/1VTkfovjfQ7L7gsJJM-9Y5O7ILkCg1xWy3Y4j426xojM/edit' }],
    img: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'tebr-project',
    title: 'Tebr Project',
    domains: ['sound','image'],
    year: '2021',
    tier: 3,
    status: 'Complete',
    desc: 'A multimedia project exploring the tebr — the lute — as carrier of diasporic memory and sonic knowledge across the Lebanese-Armenian borderlands.',
    longDesc: `The Tebr Project centers the tebr — a form of the oud specific to the Lebanese-Armenian diaspora — as a carrier of sonic knowledge that crosses linguistic and national borders. The project combines field recordings, archival photographs, oral history, and original composition to trace how a specific instrument transmits cultural memory across displacement.`,
    role: 'Artist, Researcher',
    highlights: ['The tebr (oud variant) as diasporic memory carrier', 'Field recordings, archival images, oral history, composition', 'Lebanese-Armenian borderlands'],
    links: [],
    img: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80',
    color: '#0d1208',
  },
  {
    id: '99-nodes',
    title: '99 Nodes',
    domains: ['code','systems'],
    year: '2025',
    tier: 3,
    status: 'Active',
    desc: 'Portfolio as spatial system — an interactive constellation of 74 works across 14 years, designed as navigable infrastructure rather than a CV.',
    longDesc: `99 Nodes is this portfolio site: 74 works across 14 years, arranged as a navigable constellation rather than a CV. The premise is that a practice is not a list — it is a network, and the edges between projects carry as much meaning as the nodes themselves. The Atlas (atlas-3d.html) is the primary interface.`,
    role: 'Designer, Developer',
    highlights: ['74 projects, 62 edges, navigable as constellation', '3D WebGL atlas as primary interface', 'Practice as network, not list'],
    links: [{ label: 'haigpapazian.com', url: 'https://haigpapazian.com' }],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'ibn-el-leil-visuals',
    title: 'Ibn El Leil — Visual Universe',
    domains: ['image','sound'],
    year: '2015',
    tier: 3,
    status: 'Complete',
    desc: "Visual identity and art direction for Mashrou' Leila's album Ibn El Leil. Cover, merchandise, tour design — a cohesive mythological visual system.",
    longDesc: `Ibn El Leil (Son of the Night) was Mashrou' Leila's third studio album and the record that broke the band internationally. Haig led the complete visual universe: album cover, sleeve design, merchandise system, tour staging, and visual identity. The aesthetic drew from Lebanese vernacular imagery, Islamic geometric pattern, and queer iconography — a visual language that was legible to multiple communities and owned by none.`,
    role: 'Art Director, Creative Director',
    highlights: ["Complete visual universe: cover, merch, tour design", 'Lebanese vernacular + Islamic geometric + queer iconography', 'International breakthrough record'],
    links: [],
    img: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
    color: '#0e0808',
  },
  {
    id: 'beirut-festival-set',
    title: 'Baalbeck International Festival',
    domains: ['space','sound','image'],
    year: '2017',
    tier: 3,
    status: 'Complete',
    desc: "Stage design and spatial architecture for Mashrou' Leila's performance at the Baalbeck International Festival, Lebanon.",
    longDesc: `The Baalbeck International Festival is Lebanon's oldest and most significant cultural event, held in the ruins of the Roman temples of Baalbeck. Designing a stage for this context meant designing in conversation with 2,000-year-old stone — and with the knowledge that the audience of 35,000 would include both fans of the band and people attending their first contemporary concert. The spatial language had to hold all of that simultaneously.`,
    role: 'Spatial Designer, Art Director',
    highlights: ['Baalbeck Roman ruins as performance context', 'Audience of 35,000+', 'Stage design in conversation with 2,000-year-old stone'],
    links: [],
    img: 'images/hero/mashrou-leila-baalbeck.jpg',
    color: '#100808',
  },
  {
    id: 'met-vessel-orchestra',
    title: 'MET Vessel / Orchestra',
    domains: ['space','sound'],
    year: '2019',
    tier: 3,
    status: 'Complete',
    desc: 'Spatial sound installation and performance at the Metropolitan Museum of Art. Architecture and acoustics as compositional tools.',
    longDesc: `A spatial sound installation and live performance at the Metropolitan Museum of Art, New York. The work used the museum's architecture — its specific acoustic properties, its proportions, its material surfaces — as compositional tools rather than neutral context. The audience moved through the space; the piece was different depending on where you stood.`,
    role: 'Composer, Spatial Designer',
    highlights: ['Metropolitan Museum of Art, New York', 'Architecture and acoustics as compositional tools', 'Audience in motion through the space'],
    links: [],
    img: 'https://images.unsplash.com/photo-1501386761578-eaa54b915e8f?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'barbican-performance',
    title: 'Barbican Centre, London',
    domains: ['space','sound'],
    year: '2018',
    tier: 3,
    status: 'Complete',
    desc: "Full-production concert at Barbican Centre. Spatial staging that transformed the hall's architectural language into a visual system for the set.",
    longDesc: `Full-production concert at Barbican Centre, London. The staging design took the Barbican's distinctive Brutalist architectural language — its exposed concrete, its geometric repetition, its weight — and used it as the visual system for the performance rather than working against it. The set did not decorate the hall. It read it.`,
    role: 'Spatial Designer, Art Director',
    highlights: ['Barbican Centre, London', 'Brutalist architecture as visual system', 'Staging that reads the venue rather than decorates it'],
    links: [],
    img: 'https://images.unsplash.com/photo-1501386761578-eaa54b915e8f?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'beyrouth-france-culture',
    title: 'Beyrouth et Beyrouth',
    domains: ['text','sound'],
    year: '2015',
    tier: 3,
    status: 'Published',
    desc: "Essay/lecture for France Culture exploring the divided sonic geography of Beirut — how the city's political topology maps onto its musical landscape.",
    longDesc: `Essay and lecture produced for France Culture on the sonic geography of Beirut: how the city's sectarian topology — its invisible borders, its checkpoints, its zones of sound — maps onto its musical landscape. The piece examines how music moves (or doesn't) across the city's political geography and what that mobility tells us about the nature of cultural space.`,
    role: 'Author, Lecturer',
    highlights: ['Published by France Culture', 'Beirut sonic geography and sectarian topology', 'Music as cultural mobility index'],
    links: [],
    img: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'guardian-exile',
    title: 'On Exile and Queer Arab Identity',
    domains: ['text'],
    year: '2019',
    tier: 3,
    status: 'Published',
    desc: 'Essay for The Guardian on the experience of systematic banning, queer visibility, and the political economy of silence in the Middle East.',
    longDesc: `Essay published in The Guardian on the experience of systematic cultural banning, queer visibility in the Arab world, and the political economy of silence. Written from the specific position of having built something — a band, a community, a counter-public — and having watched it be systematically removed from its context of origin by state and religious authority.`,
    role: 'Author',
    highlights: ['Published in The Guardian', 'Systematic cultural banning and queer visibility', 'Political economy of silence in the Arab world'],
    links: [],
    img: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'lamour-fait-loi',
    title: "L'Amour Fait Loi — Contributor",
    domains: ['text'],
    year: '2017',
    tier: 3,
    status: 'Published',
    desc: "Essay contribution to L'Amour Fait Loi — a collection on love, law, and LGBTQ+ rights in the Arab world.",
    longDesc: `Essay contribution to L'Amour Fait Loi, a French-language collection on love, law, and LGBTQ+ rights in the Arab world. The essay explores the tension between personal experience of queer existence and the legal and cultural infrastructure that organizes it — and what art can do in that gap.`,
    role: 'Contributing Author',
    highlights: ["Contribution to French-language collection L'Amour Fait Loi", 'Love, law, and LGBTQ+ rights in the Arab world', 'Art in the gap between experience and legal infrastructure'],
    links: [],
    img: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'beyroutes-contributor',
    title: 'Beyroutes — Contributor',
    domains: ['text','space'],
    year: '2013',
    tier: 3,
    status: 'Published',
    desc: 'Contribution to Beyroutes, a guide to alternative and off-map routes through Beirut, mapping the city\'s unofficial and counter-cultural geographies.',
    longDesc: `Contribution to Beyroutes, an alternative guide to Beirut that maps the city's unofficial, counter-cultural, and off-grid routes. The contribution focused on the sonic and spatial geography of specific neighborhoods — the parts of the city that do not appear in tourist maps because they are organized by community use rather than administrative logic.`,
    role: 'Contributing Author',
    highlights: ['Alternative guide to Beirut', 'Unofficial, counter-cultural, off-grid city routes', 'Sonic and spatial neighborhood geography'],
    links: [],
    img: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&q=80',
    color: '#120d08',
  },
  {
    id: 'sundance-fellowship',
    title: 'Sundance Institute — Art of Practice',
    domains: ['systems'],
    year: '2023',
    tier: 3,
    status: 'Complete',
    desc: 'Fellow, Sundance Institute Art of Practice program. Research and development of cross-disciplinary creative methodologies.',
    longDesc: `Fellow, Sundance Institute Art of Practice program, 2023. The fellowship supports artists developing cross-disciplinary creative methodologies and practices. The research focused on the intersection of AI research, spatial practice, and cultural strategy — specifically the systems-level thinking that connects Haig's work across domains.`,
    role: 'Fellow',
    highlights: ['Sundance Institute Art of Practice Fellow', 'Cross-disciplinary creative methodology research', 'AI research, spatial practice, cultural strategy'],
    links: [],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'ashkal-alwan-fellowship',
    title: 'Ashkal Alwan Fellowship',
    domains: ['systems','space'],
    year: '2016',
    tier: 3,
    status: 'Complete',
    desc: 'Fellowship at Ashkal Alwan (Lebanese Association for Plastic Arts), Beirut. Research on alternative art infrastructures in post-conflict environments.',
    longDesc: `Fellowship at Ashkal Alwan (Lebanese Association for Plastic Arts) in Beirut — one of the Arab world's most significant platforms for contemporary art and critical thought. The research investigated alternative art infrastructure in post-conflict environments: how cultural institutions build and maintain themselves in conditions of ongoing instability, and what models they develop that more stable contexts could learn from.`,
    role: 'Fellow',
    highlights: ['Ashkal Alwan, Beirut — leading Arab contemporary art platform', 'Alternative art infrastructure in post-conflict environments', 'Cultural institution-building under instability'],
    links: [],
    img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'bartlett-thesis',
    title: 'Bartlett Thesis — Erasure and Mediation',
    domains: ['space','text'],
    year: '2014',
    tier: 3,
    status: 'Complete',
    desc: 'MArch thesis at The Bartlett, UCL. On the erasure and mediation of place — how built environments encode memory, loss, and belonging in contested territories.',
    longDesc: `MArch thesis at The Bartlett School of Architecture, UCL, produced as a Said Foundation Scholar and British Lebanese Association Scholar. The thesis investigates the erasure and mediation of place: how built environments encode memory, loss, and belonging in contested territories — specifically Lebanon and the broader Eastern Mediterranean. The research draws on architectural history, political geography, and archival practice.`,
    role: 'Researcher, Author',
    highlights: ['MArch thesis, The Bartlett, UCL', 'Said Foundation Scholar + British Lebanese Association Scholar', 'Erasure and mediation of place in contested territories'],
    links: [],
    img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'aub-thesis',
    title: 'AUB Thesis — Threshold Architectures',
    domains: ['space'],
    year: '2010',
    tier: 3,
    status: 'Complete',
    desc: 'BArch thesis at the American University of Beirut. An investigation of threshold conditions — the architecture of between states, liminal spaces, and contested boundaries.',
    longDesc: `BArch thesis at the American University of Beirut. The thesis investigates threshold conditions: the architecture of between states — doorways, borders, checkpoints, liminal zones, contested boundaries. In Beirut, the threshold is not a design choice. It is a political condition. The thesis reads the city's architecture through its thresholds.`,
    role: 'Researcher, Author',
    highlights: ['BArch thesis, American University of Beirut', 'Threshold conditions as political architecture', 'Beirut doorways, borders, checkpoints as research object'],
    links: [],
    img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'joes-pub-residency',
    title: "Joe's Pub / The Public Theater",
    domains: ['sound','space'],
    year: '2019',
    tier: 3,
    status: 'Complete',
    desc: "Residency and performance at Joe's Pub, The Public Theater, New York. First New York performance of Space Time Tuning Machine material.",
    longDesc: `Residency and performance at Joe's Pub, The Public Theater, New York — the first New York presentation of Space Time Tuning Machine material. The residency allowed for extended development in a venue whose intimate scale and attentive audience made it possible to test the most demanding and quiet aspects of the work.`,
    role: 'Artist in Residence',
    highlights: ["Joe's Pub, The Public Theater, New York", 'First NY presentation of STTM material', 'Intimate scale — testing the quiet dimensions of the work'],
    links: [],
    img: 'https://images.unsplash.com/photo-1501386761578-eaa54b915e8f?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'sxsw-2022',
    title: 'SXSW 2022 — World Premiere',
    domains: ['sound','space'],
    year: '2022',
    tier: 3,
    status: 'Complete',
    desc: 'World premiere of Space Time Tuning Machine at SXSW, Austin. The full performance installation presented for the first time as a complete spatial work.',
    longDesc: `World premiere of Space Time Tuning Machine as a complete spatial work at SXSW, Austin, 2022. The performance marked the first time the work was presented in its full installation form — as an environment to be inhabited rather than a concert to be watched. The premiere was followed by a presentation at The Broad Museum in Los Angeles.`,
    role: 'Artist, Performer',
    highlights: ['World premiere of Space Time Tuning Machine', 'SXSW 2022, Austin', 'Complete installation form — environment, not concert'],
    links: [],
    img: 'images/hero/sxsw-2022.jpg',
    color: '#100808',
  },
  {
    id: 'the-broad-la',
    title: 'The Broad Museum, Los Angeles',
    domains: ['sound','space'],
    year: '2022',
    tier: 3,
    status: 'Complete',
    desc: 'Performance and installation at The Broad Museum, Los Angeles. Space Time Tuning Machine as site-specific spatial audio work.',
    longDesc: `Performance and installation at The Broad Museum, Los Angeles, 2022. Space Time Tuning Machine was presented as a site-specific spatial audio work: the museum's architecture — its veil-and-vault structure, its specific acoustic character — became part of the composition. Following the SXSW world premiere, this presentation demonstrated the work's adaptability to different spatial conditions.`,
    role: 'Artist, Spatial Designer',
    highlights: ['The Broad Museum, Los Angeles', 'Site-specific spatial audio — museum architecture as composition', 'Following SXSW world premiere'],
    links: [],
    img: 'https://images.unsplash.com/photo-1501386761578-eaa54b915e8f?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'npr-feature',
    title: "NPR Feature — Mashrou' Leila",
    domains: ['sound','text'],
    year: '2019',
    tier: 3,
    status: 'Published',
    desc: "Featured profile and interview on NPR covering the political dimensions of Mashrou' Leila's work and the economics of protest music.",
    longDesc: `Featured profile and interview on NPR covering the political dimensions of Mashrou' Leila's work, the economics of protest music, and what it means to build a cultural infrastructure that can be banned. The piece reached audiences who had not previously encountered the band and became one of the primary international framing documents for the band's final years.`,
    role: 'Subject',
    highlights: ['NPR featured profile, 2019', 'Political dimensions and economics of protest music', 'International framing document for the band'],
    links: [],
    img: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    color: '#100808',
  },
  {
    id: 'columbia-lecture',
    title: 'Columbia University — Lecture',
    domains: ['text','systems'],
    year: '2020',
    tier: 3,
    status: 'Complete',
    desc: 'Invited lecture at Columbia University on systems choreography, the politics of creative infrastructure, and the Localization Gap thesis.',
    longDesc: `Invited lecture at Columbia University on systems choreography, the politics of creative infrastructure, and early iterations of what would become the Localization Gap thesis. The talk addressed how working across disciplines at angles — diagonally — produces insights unavailable to either domain-specific depth or horizontal breadth.`,
    role: 'Lecturer',
    highlights: ['Invited lecture, Columbia University', 'Systems choreography and diagonal logic', 'Early Localization Gap thesis'],
    links: [],
    img: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80',
    color: '#0a100c',
  },
  {
    id: 'dartmouth-lecture',
    title: 'Dartmouth College — Lecture',
    domains: ['text','systems'],
    year: '2021',
    tier: 3,
    status: 'Complete',
    desc: 'Invited lecture at Dartmouth College on multidisciplinary practice, exile architecture, and the cultural politics of sound.',
    longDesc: `Invited lecture at Dartmouth College on multidisciplinary practice, exile architecture, and the cultural politics of sound. The lecture explored how the experience of building a band in Beirut — and then having it systematically banned — produces specific forms of architectural and systemic thinking about how cultural space is made and unmade.`,
    role: 'Lecturer',
    highlights: ['Invited lecture, Dartmouth College', 'Exile architecture and cultural politics of sound', 'Building and unmaking cultural space'],
    links: [],
    img: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80',
    color: '#0a100c',
  },
  {
    id: 'sciences-po-lecture',
    title: 'Sciences Po — Lecture',
    domains: ['text','systems'],
    year: '2019',
    tier: 3,
    status: 'Published',
    desc: 'Invited lecture at Sciences Po Paris on the geopolitical dimensions of popular music, cultural bans, and the infrastructure of censorship.',
    longDesc: `Invited lecture at Sciences Po Paris on the geopolitical dimensions of popular music: how cultural bans operate, what infrastructure they require, and how artists and their communities respond. The lecture situated Mashrou' Leila's experience within a broader analysis of censorship as political technology.`,
    role: 'Lecturer',
    highlights: ['Invited lecture, Sciences Po Paris', 'Geopolitical dimensions of popular music', 'Censorship as political technology'],
    links: [],
    img: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80',
    color: '#0a100c',
  },
  {
    id: 'nobel-peace-center',
    title: 'Nobel Peace Center',
    domains: ['sound','text'],
    year: '2020',
    tier: 3,
    status: 'Complete',
    desc: 'Presentation and performance at the Nobel Peace Center, Oslo. On music as political infrastructure and the architecture of cultural resistance.',
    longDesc: `Presentation and performance at the Nobel Peace Center, Oslo. The work addressed music as political infrastructure — not as expression of political sentiment, but as a system that creates and maintains communities in conditions where other forms of assembly are prohibited. The Nobel Peace Center context gave the presentation a specific resonance: peace as the absence of the conditions that make resistance necessary.`,
    role: 'Artist, Presenter',
    highlights: ['Nobel Peace Center, Oslo', 'Music as political infrastructure, not expression', 'Cultural resistance as system, not sentiment'],
    links: [],
    img: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80',
    color: '#0a100c',
  },
  {
    id: 'itp-camp-2024',
    title: 'NYU ITP Camp 2024',
    domains: ['code','systems'],
    year: '2024',
    tier: 3,
    status: 'Complete',
    desc: 'Participant, NYU Tisch ITP Camp 2024. Experimental computing, creative technology, and interdisciplinary making.',
    longDesc: `Participant in NYU Tisch ITP Camp 2024 — a two-week intensive at one of the world's premier experimental computing and creative technology programs. The camp accelerated the technical dimensions of the Localization Gap research and catalyzed the development of Lede.nyc's technical architecture.`,
    role: 'Participant',
    highlights: ['NYU Tisch ITP Camp 2024', 'Experimental computing, creative technology', 'Catalyzed Localization Gap research and Lede.nyc architecture'],
    links: [],
    img: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80',
    color: '#080d0d',
  },
  {
    id: 'jean-nouvel-collaboration',
    title: 'Ateliers Jean Nouvel',
    domains: ['space'],
    year: '2012',
    tier: 3,
    status: 'Complete',
    desc: 'Architectural practice at Ateliers Jean Nouvel, Paris. Working at the intersection of technical precision and conceptual ambition in built form.',
    longDesc: `Architectural practice at Ateliers Jean Nouvel, Paris, 2012. Working within one of the world's most conceptually ambitious practices at the intersection of technical precision and formal experimentation. The experience of working at this scale — on buildings that will stand for a century — shaped the systems-level thinking that runs through all subsequent work.`,
    role: 'Architect',
    highlights: ['Ateliers Jean Nouvel, Paris', 'Technical precision + conceptual ambition in built form', 'Systems-level thinking at architectural scale'],
    links: [],
    img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'impossible-futures',
    title: 'Impossible Futures Framework',
    domains: ['systems','text'],
    year: '2024',
    tier: 3,
    status: 'Active',
    desc: 'Framework for imagining and designing toward futures that are currently structurally blocked.',
    longDesc: `The Impossible Futures Framework addresses a specific problem: how do you design toward a future that is currently structurally blocked? Not utopian, not aspirational — specifically blocked by existing systems, power structures, and resource distributions. The framework applies scenario planning, counterfactual analysis, and speculative design methods to identify the structural levers that would need to shift. Applied to cultural strategy, urban design, and AI systems.`,
    role: 'Theorist',
    highlights: ['Futures structurally blocked by existing systems', 'Scenario planning + counterfactual analysis + speculative design', 'Applied to cultural strategy, urban design, AI systems'],
    links: [],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'meaning-stack',
    title: 'The Meaning Stack',
    domains: ['systems','code'],
    year: '2024',
    tier: 3,
    status: 'Active',
    desc: 'Architecture for understanding how meaning is constructed across layers — from raw material to cultural resonance.',
    longDesc: `The Meaning Stack is an architecture for understanding how meaning is constructed across layers — from raw material (sound, pixel, word, line of code) through technical processing, compositional structure, aesthetic experience, cultural context, and finally to resonance in a specific community. The framework organizes the GitHub repos (DERIVE, HAH-WAS, STORYLINES, music-engines, photon+) as a coherent system rather than separate projects.`,
    role: 'Theorist, Architect',
    highlights: ['Meaning constructed across layers from raw material to resonance', 'Organizes GitHub repos as coherent system', 'Framework: DERIVE, HAH-WAS, STORYLINES, music-engines, photon+'],
    links: [],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'navigating-latency',
    title: 'Navigating Latency',
    domains: ['systems','text'],
    year: '2024',
    tier: 3,
    status: 'Active',
    desc: 'Framework for operating in conditions of systemic delay or friction.',
    longDesc: `Navigating Latency is a framework for operating in conditions of systemic delay or friction — censorship, institutional drag, bureaucratic obstruction, funding gaps, platform restriction. The framework draws on the experience of building creative infrastructure in Beirut and the Arab world, where the latency between intention and execution is often measured in years or in permanent blockage. Applied to creative production under restriction, and to AI systems that fail to respond to cultural context at the moment of need.`,
    role: 'Theorist',
    highlights: ['Operating under censorship, institutional drag, and systemic friction', 'Drawn from creative infrastructure in Beirut and Arab world', 'Applied to AI cultural latency'],
    links: [],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'diagonal-logic',
    title: 'Diagonal Logic',
    domains: ['systems','text'],
    year: '2024',
    tier: 3,
    status: 'Active',
    desc: 'Working across disciplines at angles — not horizontally within a field, or vertically in depth, but diagonally finding connective tissue between domains.',
    longDesc: `Diagonal Logic is the operating principle behind the entire practice. Working horizontally (across a field) produces breadth without depth. Working vertically (within a field) produces depth without perspective. Working diagonally — across disciplines at angles — finds the connective tissue between domains that neither can see from inside itself. Architecture informs music. Music informs code. Code informs writing. Writing informs architecture. The angle is where the insight lives.`,
    role: 'Theorist',
    highlights: ['Horizontal = breadth; vertical = depth; diagonal = connective tissue', 'Architecture → music → code → writing → architecture', 'The angle is where the insight lives'],
    links: [],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'subtractive-composition',
    title: 'Subtractive Composition',
    domains: ['sound','systems'],
    year: '2023',
    tier: 3,
    status: 'Active',
    desc: 'Music as excavation rather than addition. Practice-as-research drawing on Basinski, Caretaker, Pauline Oliveros, King Tubby, and Berlin Reductionism.',
    longDesc: `Subtractive Composition is both a practice and a research framework. The premise: most music is additive — you start from silence and build. Subtractive composition starts from complexity and removes until something true remains. It is excavation, not construction. The tradition includes William Basinski's Disintegration Loops, The Caretaker's memory-eroded hauntology, Pauline Oliveros's Deep Listening practice, King Tubby's mixing desk as subtractive instrument, Brian Eno's oblique removal strategies, and the Berlin Reductionism scene. The Space Time Tuning Machine is its most complete application.`,
    role: 'Composer, Researcher',
    highlights: ['Music as excavation, not construction', 'Tradition: Basinski, Caretaker, Oliveros, King Tubby, Eno, Berlin Reductionism', 'STTM as primary application'],
    links: [],
    img: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80',
    color: '#0d1208',
  },
  {
    id: 'yo-yo-ma-collab',
    title: 'Yo-Yo Ma — Collaboration',
    domains: ['sound','space'],
    year: '2019',
    tier: 3,
    status: 'Complete',
    desc: "Collaboration with Yo-Yo Ma. Bringing the Mashrou' Leila sonic vocabulary into dialogue with Western classical tradition and global chamber music contexts.",
    longDesc: `Collaboration with Yo-Yo Ma in 2019, bringing the Mashrou' Leila sonic vocabulary into dialogue with Western classical tradition and global chamber music contexts. The collaboration explored what happens when the specific harmonic and tonal language of contemporary Arab music meets the Western classical cello — and what each tradition learns from the encounter.`,
    role: 'Collaborator',
    highlights: ["Collaboration with Yo-Yo Ma", "Arab harmonic language meets Western classical cello", "Chamber music as cross-cultural encounter"],
    links: [],
    img: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80',
    color: '#0d1208',
  },
  {
    id: 'mika-collab',
    title: 'Mika — Collaboration',
    domains: ['sound','image'],
    year: '2018',
    tier: 3,
    status: 'Complete',
    desc: 'Creative collaboration with Mika on visual identity, touring design, and the intersection of Middle Eastern pop aesthetics with European performance culture.',
    longDesc: `Creative collaboration with Mika on visual identity, touring design, and the intersection of Middle Eastern pop aesthetics with European performance culture. The collaboration bridged two distinct visual and sonic traditions: Mika's theatrical, maximalist European pop language and the more architecturally restrained but politically charged aesthetic of Mashrou' Leila.`,
    role: 'Creative Director',
    highlights: ['Visual identity and touring design', 'Middle Eastern pop aesthetics + European performance culture', 'Architectural restraint meets theatrical maximalism'],
    links: [],
    img: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    color: '#0d0810',
  },
  {
    id: 'kardia-prd',
    title: 'Kardia — Full PRD',
    domains: ['code','text','systems'],
    year: '2026',
    tier: 3,
    status: 'Complete',
    desc: 'Complete Product Requirements Document for Kardia biofeedback synthesizer. 60+ pages covering architecture, UX, audio engine, biosignal processing.',
    longDesc: `The complete Product Requirements Document for Kardia, completed January 2026. 60+ pages covering the full product architecture: UX interaction model, audio engine specification (AudioKit/Oboe), biosignal processing pipeline (heart rate abstraction into harmonic density), offline-first data architecture (SQLite), Scala file export for cardiac scales, and the underlying research into the Iso-Principle and music therapy applications.`,
    role: 'Product Architect, Author',
    highlights: ['60+ page PRD, completed January 2026', 'Full architecture: UX, audio engine, biosignal processing, data', 'Iso-Principle research and music therapy applications'],
    links: [],
    img: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    color: '#0a0d14',
  },
  {
    id: 'epistemic-defense',
    title: 'Epistemic Defense',
    domains: ['systems','text'],
    year: '2024',
    tier: 3,
    status: 'Active',
    desc: 'Framework for maintaining intellectual integrity in high-noise information environments.',
    longDesc: `Epistemic Defense is a framework for maintaining intellectual integrity in high-noise information environments: how to think clearly when the information landscape is designed to produce confusion, how to distinguish signal from noise when noise is indistinguishable from signal, and how to maintain a research practice under conditions of epistemic attack. Applied to AI research, cultural criticism, and archival practice.`,
    role: 'Theorist',
    highlights: ['Intellectual integrity under epistemic attack', 'Signal/noise under conditions of designed confusion', 'Applied to AI research and cultural criticism'],
    links: [],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'arabic-maqam-research',
    title: 'Arabic Maqam Research',
    domains: ['sound','text','code'],
    year: '2023',
    tier: 3,
    status: 'Active',
    desc: 'Foundational research into maqam systems — microtonal structures, modal hierarchies, and the Western AI failure modes that erase them.',
    longDesc: `Foundational research into Arabic maqam systems: their microtonal structures, modal hierarchies, the role of the saba and rast registers in emotional and cultural signaling, and the specific failure modes that occur when Western AI systems attempt to reproduce them. This research is the precursor to the Localization Gap Audit and provides the theoretical framework for evaluating what AI-generated music actually does when it attempts to be Arabic.`,
    role: 'Researcher',
    highlights: ['Maqam structures: microtonal, modal, emotional, cultural', 'Western AI failure modes under maqam prompting', 'Precursor and theoretical frame for the Localization Gap'],
    links: [],
    img: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80',
    color: '#0d1208',
  },
  {
    id: 'westbeth-safe-haven',
    title: 'Westbeth Safe Haven',
    domains: ['space','systems'],
    year: '2024',
    tier: 3,
    status: 'Active',
    desc: "MEKENA NYC's partnership with Westbeth Artists Housing to provide emergency residency and support infrastructure for artists in crisis.",
    longDesc: `MEKENA NYC's partnership with Westbeth Artists Housing — a protected affordable housing complex for artists in the West Village that has housed artists since 1970. The Safe Haven partnership provides emergency residency access for artists in crisis: displacement, eviction, domestic violence, sudden loss of housing. The infrastructure is designed to reduce the bureaucratic friction of the emergency moment.`,
    role: 'Program Director',
    highlights: ['Emergency residency access for artists in crisis', 'Partnership with Westbeth Artists Housing (est. 1970)', 'Reducing bureaucratic friction at the moment of emergency'],
    links: [],
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    color: '#0c0c08',
  },
  {
    id: 'beirut-sonic-map',
    title: 'Beirut Sonic Map',
    domains: ['sound','space','image'],
    year: '2020',
    tier: 3,
    status: 'Complete',
    desc: 'A cartographic project mapping the acoustic geography of pre- and post-2020 blast Beirut — sound as urban memory and evidence.',
    longDesc: `Beirut Sonic Map is a cartographic project documenting the acoustic geography of Beirut before and after the August 2020 port explosion. Sound as urban memory: the specific ambient signatures of neighborhoods, the acoustic changes produced by mass destruction, the sonic evidence that remains when visual evidence is removed. The map was assembled from field recordings, archival audio, and community-submitted clips.`,
    role: 'Artist, Researcher',
    highlights: ['Pre- and post-2020 blast acoustic geography of Beirut', 'Sound as urban memory and forensic evidence', 'Field recordings + archival audio + community submissions'],
    links: [],
    img: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80',
    color: '#0a100c',
  },
  {
    id: 'archive-of-bans',
    title: 'Archive of Bans',
    domains: ['systems','text'],
    year: '2023',
    tier: 3,
    status: 'Active',
    desc: "A living archive documenting the systematic banning of Mashrou' Leila across MENA — each ban categorized by mechanism, jurisdiction, and political context.",
    longDesc: `A living archive documenting the systematic banning of Mashrou' Leila across the MENA region. Each ban is categorized by mechanism (state directive, religious authority, venue pressure, platform restriction), jurisdiction, date, political context, and outcome. The archive is both a research resource and an act of witness: naming the systems of erasure precisely so they cannot be dismissed as isolated incidents. The archive is ongoing.`,
    role: 'Archivist, Researcher',
    highlights: ['Every ban categorized: mechanism, jurisdiction, political context', 'State directive, religious authority, venue pressure, platform restriction', 'Research resource and act of witness simultaneously'],
    links: [],
    img: 'https://images.unsplash.com/photo-1590608897129-79da98d15969?w=800&q=80',
    color: '#100c08',
  },
  {
    id: 'lede-nyc-strategy',
    title: 'Lede.nyc — Strategy Document',
    domains: ['systems','code','text'],
    year: '2025',
    tier: 3,
    status: 'Active',
    desc: 'Comprehensive 40-section strategic document covering competitive forensics, feature framework, UI evolution, and monetization for Lede.nyc.',
    longDesc: `The comprehensive strategic document for Lede.nyc: 40 sections covering competitive forensics (Nextdoor, Citizen, StreetEasy, Patch), feature framework (Lease Due Diligence Engine, Scaffold Duration Forecasting, Block Mood Forecast, Canine Commute Optimizer), UI evolution roadmap, LLM orchestration architecture, data ingestion pipeline design, and five-tier monetization model targeting $5M+ ARR.`,
    role: 'Author, Strategist',
    highlights: ['40-section strategy document', 'Competitive forensics + feature framework + monetization', 'Five-tier model targeting $5M+ ARR'],
    links: [],
    img: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    color: '#060a10',
  },
  {
    id: 'the-waw-signal',
    title: 'The Waw Signal',
    domains: ['sound','systems','image'],
    year: '2025',
    tier: 3,
    status: 'Active',
    desc: "Visual-sonic research project centered on the Arabic letter و (waw) as waveform, heartbeat spike, and hook — the generative mark behind Walaw Studio's identity.",
    longDesc: `The Waw Signal is a visual-sonic research project centered on a single mark: و, the Arabic letter waw. Read as a waveform it is a single cycle of sound. Read as a medical readout it is a heartbeat spike. Read as typography it is a hook. As the conjunction "and" it is the simplest connector — the thing that holds separate elements in relation without merging them. The project explores the waw as a generative form: what can be built from a mark that is simultaneously sound, image, text, and connection.`,
    role: 'Artist, Researcher',
    highlights: ['Arabic و (waw) as waveform, heartbeat, hook, conjunction', 'Single mark as generative form across domains', 'Foundation of Walaw Studio visual identity'],
    links: [],
    img: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=800&q=80',
    color: '#0a0c12',
  },
];

/* ── DOMAIN COLOR MAP ──────────────────────────────────────────── */
const DOMAIN_COLORS = {
  sound: '#b8966a', text: '#5b8a7a', image: '#8a5b7a',
  code: '#4a7a8a', space: '#7a8a4a', systems: '#7a5a8a'
};
const DOMAIN_LABELS = {
  sound: 'Sound', text: 'Text', image: 'Image',
  code: 'Code', space: 'Space', systems: 'Systems'
};

const RAW_EDGES = [
  ['mashrou-leila','rolling-stone-cover'],['mashrou-leila','ibn-el-leil-visuals'],
  ['mashrou-leila','beirut-festival-set'],['mashrou-leila','barbican-performance'],
  ['mashrou-leila','met-vessel-orchestra'],['mashrou-leila','yo-yo-ma-collab'],
  ['mashrou-leila','mika-collab'],['mashrou-leila','archive-of-bans'],
  ['mashrou-leila','cost-of-queer-arab'],['mashrou-leila','walaw-studio'],
  ['mashrou-leila','space-time-tuning-machine'],
  ['space-time-tuning-machine','sxsw-2022'],['space-time-tuning-machine','the-broad-la'],
  ['space-time-tuning-machine','photon-plus'],['space-time-tuning-machine','subtractive-composition'],
  ['space-time-tuning-machine','caspian-mare-drift'],['space-time-tuning-machine','beirut-sonic-map'],
  ['localization-gap-audit','music-engines'],['localization-gap-audit','arabic-maqam-research'],
  ['localization-gap-audit','ai-music-archive'],['localization-gap-audit','walaw-studio'],
  ['localization-gap-audit','harmonic-field-research'],
  ['cartography-of-absence','sometimes-i-wake-up-elsewhere'],['cartography-of-absence','crane-song'],
  ['cartography-of-absence','bureaucratic-surrealism'],['crane-song','souad-novella'],
  ['crane-song','the-forgery'],
  ['walaw-studio','mekena-nyc-initiative'],['walaw-studio','systems-choreography'],
  ['walaw-studio','meaning-stack'],['walaw-studio','the-waw-signal'],
  ['walaw-studio','westbeth-safe-haven'],
  ['lede-nyc','lede-nyc-strategy'],['lede-nyc','itp-camp-2024'],
  ['kardia-system','kardia-prd'],['kardia-system','music-engines'],['kardia-system','mobius-engine'],
  ['derive-engine','hah-was-sieve'],['derive-engine','storylines-graph'],['derive-engine','99-nodes'],
  ['loop-corridor','codeverse-explorer'],['codeverse-explorer','99-nodes'],
  ['bartlett-thesis','aub-thesis'],['bartlett-thesis','architecture-in-low-res'],
  ['bartlett-thesis','jean-nouvel-collaboration'],['ashkal-alwan-fellowship','bartlett-thesis'],
  ['mekena-nyc-initiative','westbeth-safe-haven'],['mekena-nyc-initiative','sundance-fellowship'],
  ['arabic-maqam-research','localization-gap-audit'],['colors-baby','ai-music-archive'],
  ['meaning-stack','systems-choreography'],['impossible-futures','diagonal-logic'],
  ['beirut-sonic-map','beirut-festival-set'],['tebr-project','beirut-sonic-map'],
  ['guardian-exile','cost-of-queer-arab'],['guardian-exile','archive-of-bans'],
  ['3d-beat-synth','harmonic-field-research'],['music-engines','harmonic-field-research'],
  ['ghost-city-sculpture','architecture-in-low-res'],['project-agora','menara-infrastructure'],
  ['the-labyrinth','loop-corridor'],['beyrouth-france-culture','beirut-sonic-map'],
  ['npr-feature','cost-of-queer-arab'],['epistemic-defense','meaning-stack'],
  ['lede-nyc','walaw-studio'],['kardia-system','walaw-studio'],
  ['barbican-performance','sxsw-2022'],['ibn-el-leil-visuals','rolling-stone-cover'],
];

// Supports both browser and Node.js
if (typeof window !== 'undefined') {
  window.PROJECTS = PROJECTS;
  window.DOMAIN_COLORS = DOMAIN_COLORS;
  window.DOMAIN_LABELS = DOMAIN_LABELS;
  window.RAW_EDGES = RAW_EDGES;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PROJECTS, DOMAIN_COLORS, DOMAIN_LABELS, RAW_EDGES };
}
